trigger:
  branches:
    include:
      - main2  # Adjust the branch if needed

pool:
  vmImage: "ubuntu-latest"

variables:
  RESOURCE_GROUP: 'ml-chatbot-new-rg'  # Updated resource group name to match your new deployment
  # We can remove most environment variables since they're now set in Bicep

stages:
  - stage: Package_FunctionApp
    displayName: "Package Function App Code"
    jobs:
      - job: ArchiveFunctionApp
        displayName: "Archive Function App"
        steps:
          - script: |
              python -m pip install --upgrade pip
              pip install azure-ai-vision-imageanalysis
              pip install -r function-app/fetch_data/requirements.txt -t function-app/fetch_data/
            displayName: "Install Python Dependencies"

          - task: ArchiveFiles@2
            displayName: "Archive Function App Code"
            inputs:
              rootFolderOrFile: "function-app/fetch_data/"
              includeRootFolder: true
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/function-app.zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish Function App Artifact"
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)/function-app.zip"
              artifactName: "FunctionApp"

  - stage: Deploy_FunctionApp
    displayName: "Deploy Function App to Azure"
    dependsOn: 
      - Package_FunctionApp
    jobs:
      - job: DeployFunctionApp
        displayName: "Deploy Function App"
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: "Download Function App Artifact"
            inputs:
              artifact: "FunctionApp"
              path: "$(Pipeline.Workspace)/FunctionApp"

          - task: AzureFunctionApp@1
            displayName: "Deploy to Azure Function"
            inputs:
              azureSubscription: "CloudSageAI-SP"
              appName: "ml-chatbot-new-api"  # Updated to match Bicep template
              package: "$(Pipeline.Workspace)/FunctionApp/function-app.zip"
              # No need for additional app settings configuration