trigger:
  branches:
    include:
      - testingapp2

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build_And_Push_Images
    displayName: "Build and Push Docker Images"
    jobs:
      - job: BuildDockerImages
        displayName: "Build and Push UI & API Docker Images"
        steps:
          - task: Docker@2
            displayName: "Login to ACR"
            inputs:
              command: "login"
              containerRegistry: "CloudSageAI-ACR" # Use the Docker Registry service connection name

          - task: Docker@2
            displayName: "Build and Push UI Image"
            inputs:
              command: "buildAndPush"
              repository: "mlchatbotacr.azurecr.io/chatbot-ui"  # Explicit ACR name
              dockerfile: "ui/Dockerfile"
              containerRegistry: "CloudSageAI-ACR" # Use the Docker Registry service connection name
              tags: "latest"

          - task: Docker@2
            displayName: "Build and Push API Image"
            inputs:
              command: "buildAndPush"
              repository: "mlchatbotacr.azurecr.io/chatbot-api" # Explicit ACR name
              dockerfile: "api/Dockerfile"
              containerRegistry: "CloudSageAI-ACR" # Use the Docker Registry service connection name
              tags: "latest"