apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          image: YOUR_AZURE_CONTAINER_REGISTRY.azurecr.io/chatbot-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://chatbot-api-service:3001"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
  labels:
    app: chatbot-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
        - name: chatbot-api
          image: YOUR_AZURE_CONTAINER_REGISTRY.azurecr.io/chatbot-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: AZURE_OPENAI_ENDPOINT
              value: "https://your-openai-instance.openai.azure.com"
            - name: AZURE_COGNITIVE_SEARCH_ENDPOINT
              value: "https://your-cognitive-search-instance.search.windows.net"
            - name: AZURE_COSMOSDB_ENDPOINT
              value: "https://your-cosmosdb-instance.documents.azure.com"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
