trigger:
  branches:
    include:
      - main2

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Deploy_Infrastructure
    displayName: "Deploy Infrastructure using Bicep"
    jobs:
      - job: CreateResourceGroup
        displayName: "Ensure Resource Group Exists"
        steps:
          - task: AzureCLI@2
            displayName: "Create Resource Group"
            inputs:
              azureSubscription: "CloudSageAI-SP"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                rg_name="ml-chatbot-new-rg"
                rg_location="westeurope"
                if ! az group show --name $rg_name &>/dev/null; then
                  az group create --name $rg_name --location $rg_location
                else
                  echo "Resource group $rg_name already exists in location $rg_location"
                fi

      - job: DeployBicep
        displayName: "Deploy Bicep Templates"
        dependsOn: CreateResourceGroup  # Ensure RG exists before deploying resources
        steps:
          - task: AzureCLI@2
            displayName: "Deploy Bicep"
            inputs:
              azureSubscription: "CloudSageAI-SP"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group create --resource-group ml-chatbot-new-rg --template-file bicep/deploy.bicep
